# Set up the service account permissions to be able to deploy INSIDE
# the cluster from a deploy-bot container.

# See: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: zgw
  name: deployer
rules:
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "patch"]

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: deploy-bot
  namespace: zgw
automountServiceAccountToken: true

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: patch-deployments
  namespace: zgw
subjects:
- kind: ServiceAccount
  name: deploy-bot
  namespace: zgw
roleRef:
  kind: Role
  name: deployer
  apiGroup: rbac.authorization.k8s.io
