---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ service.name }}-private-media
  namespace: zgw
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
