---


# Runtime secrets. Values are base64 encoded

kind: Secret
apiVersion: v1
metadata:
  name: {{ service.name }}-secrets
  namespace: zgw
type: Opaque
data:
  DB_PASSWORD: {{ db_password | b64encode }}
