---

# Runtime secrets. Values are base64 encoded

kind: Secret
apiVersion: v1
metadata:
  name: zrc-secrets
  namespace: zgw
type: Opaque
data:
  SECRET_KEY: <REDACTED>
  DB_PASSWORD: <REDACTED>
  SENTRY_DSN: <REDACTED>

---

# Deployment

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: zrc
  namespace: zgw
  labels:
    k8s-app: zrc
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: zrc
  template:
    metadata:
      name: zrc
      labels:
        k8s-app: zrc
    spec:
      containers:
      - name: zrc
        image: vngr/gemma-zrc:0.17.0
        resources:
          requests:
            memory: "200Mi"
            cpu: "5m"
          limits:
            memory: "500Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /
            port: 8000
            httpHeaders:
              - name: Host
                value: localhost
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8000
            httpHeaders:
              - name: Host
                value: localhost
          initialDelaySeconds: 5
          periodSeconds: 5

        env:
          - name: DJANGO_SETTINGS_MODULE
            value: zrc.conf.docker
          - name: DB_HOST
            value: postgis
          - name: DB_NAME
            value: zrc
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: zrc-secrets
                key: SECRET_KEY
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: zrc-secrets
                key: DB_PASSWORD
          - name: SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: zrc-secrets
                key: SENTRY_DSN

---

# Service

kind: Service
apiVersion: v1
metadata:
  name: zrc
  namespace: zgw
  labels:
    k8s-app: zrc
spec:
  selector:
    k8s-app: zrc
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
