---

# Deployment

kind: Deployment
apiVersion: apps/v1
metadata:
  name: rabbitmq-{{ service.name }}
  namespace: zgw
  labels:
    k8s-app: rabbitmq-{{ service.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: rabbitmq-{{ service.name }}
  template:
    metadata:
      name: rabbitmq-{{ service.name }}
      labels:
        k8s-app: rabbitmq-{{ service.name }}
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.7-alpine
        env:
          - name: RABBITMQ_DEFAULT_USER
            valueFrom:
              secretKeyRef:
                name: {{ service.name }}-secrets
                key: RABBITMQ_DEFAULT_USER
          - name: RABBITMQ_DEFAULT_PASS
            valueFrom:
              secretKeyRef:
                name: {{ service.name }}-secrets
                key: RABBITMQ_DEFAULT_PASS

---

# Service

kind: Service
apiVersion: v1
metadata:
  name: rabbitmq-{{ service.name }}
  namespace: zgw
  labels:
    k8s-app: rabbitmq-{{ service.name }}
spec:
  selector:
    k8s-app: rabbitmq-{{ service.name }}
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672
