---

# Runtime secrets. Values are base64 encoded

kind: Secret
apiVersion: v1
metadata:
  name: {{ service.name }}-secrets
  namespace: zgw
type: Opaque
data:
  SECRET_KEY: {{ secret_keys.nrc | b64encode }}
  DB_PASSWORD: {{ db_password | b64encode }}
  RABBITMQ_DEFAULT_USER: {{ rabbitmq.default_user | b64encode }}
  RABBITMQ_DEFAULT_PASS: {{ rabbitmq.default_pass | b64encode }}
  PUBLISH_BROKER_URL: {{ nrc_celery.publish_broker_url | b64encode }}
  CELERY_BROKER_URL: {{ nrc_celery.broker_url | b64encode }}
  CELERY_RESULT_BACKEND: {{ nrc_celery.result_backend | b64encode }}
  SENTRY_DSN: {% if sentry_dsns.nrc %}{{ sentry_dsns.nrc | b64encode }}{% else %}''{% endif %}
