---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{ ingress.name }}
  namespace: zgw
  labels:
    app.kubernetes.io/instance: zgw-{{ ingress.instance }}
    app.kubernetes.io/name: zgw
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    {% for service in ingress.services -%}
    - host: {{ service.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ service.name }}
              servicePort: {{ service.port | default(8000) }}
    {% endfor %}

  tls:
    {% for service in ingress.services -%}
    - hosts:
      - {{ service.host }}
      secretName: {{ service.name }}-tls
    {% endfor %}
