---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: drc-private-media
  namespace: zgw
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi

---

# Runtime secrets. Values are base64 encoded

# kind: Secret
# apiVersion: v1
# metadata:
#   name: drc-secrets
#   namespace: zgw
# type: Opaque
# data:
#   SECRET_KEY: <REDACTED>
#   DB_PASSWORD: <REDACTED>
#   SENTRY_DSN: <REDACTED>

---

# Deployment

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: drc
  namespace: zgw
  labels:
    k8s-app: drc
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: drc
  template:
    metadata:
      name: drc
      labels:
        k8s-app: drc
    spec:
      containers:
      - name: drc
        image: vngr/gemma-drc:0.14.0
        resources:
          requests:
            memory: "120Mi"
            cpu: "5m"
          limits:
            memory: "350Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /
            port: 8000
            httpHeaders:
              - name: Host
                value: localhost
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8000
            httpHeaders:
              - name: Host
                value: localhost
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
          - name: DJANGO_SETTINGS_MODULE
            value: drc.conf.docker
          - name: DB_HOST
            value: postgis
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: drc-secrets
                key: SECRET_KEY
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: drc-secrets
                key: DB_PASSWORD
          - name: SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: drc-secrets
                key: SENTRY_DSN
        volumeMounts:
          - name: private-storage
            mountPath: /app/private-media
            subPath: zgw/drc/private-media
      volumes:
        - name: private-storage
          persistentVolumeClaim:
            claimName: drc-private-media

---

# Service

kind: Service
apiVersion: v1
metadata:
  name: drc
  namespace: zgw
  labels:
    k8s-app: drc
spec:
  selector:
    k8s-app: drc
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
