---

# Deployment

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nrc
  namespace: zgw
  labels:
    k8s-app: nrc
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: nrc
  template:
    metadata:
      name: nrc
      labels:
        k8s-app: nrc
    spec:
      containers:
      - name: nrc
        image: vngr/gemma-notifications:0.7.0
        resources:
          requests:
            memory: "150Mi"
            cpu: "5m"
          limits:
            memory: "350Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /
            port: 8000
            httpHeaders:
              - name: Host
                value: localhost
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8000
            httpHeaders:
              - name: Host
                value: localhost
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
          - name: DJANGO_SETTINGS_MODULE
            value: notifications.conf.docker
          - name: DB_HOST
            value: postgis
          - name: DB_NAME
            value: nrc
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: nrc-secrets
                key: SECRET_KEY
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nrc-secrets
                key: DB_PASSWORD
          - name: SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: nrc-secrets
                key: SENTRY_DSN
          - name: PUBLISH_BROKER_URL
            valueFrom:
              secretKeyRef:
                name: nrc-secrets
                key: PUBLISH_BROKER_URL
          - name: CELERY_BROKER_URL
            valueFrom:
              secretKeyRef:
                name: nrc-secrets
                key: CELERY_BROKER_URL
          - name: CELERY_RESULT_BACKEND
            valueFrom:
              secretKeyRef:
                name: nrc-secrets
                key: CELERY_RESULT_BACKEND

---

# Service

kind: Service
apiVersion: v1
metadata:
  name: nrc
  namespace: zgw
  labels:
    k8s-app: nrc
spec:
  selector:
    k8s-app: nrc
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
