---

# Deployment

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: docs
  namespace: zgw
  labels:
    k8s-app: docs
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: docs
  template:
    metadata:
      name: docs
      labels:
        k8s-app: docs
    spec:
      containers:
      - name: docs
        image: vngr/gemma-zaken-docs:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "10Mi"
            cpu: "5m"
          limits:
            memory: "100Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80


---

# Service

kind: Service
apiVersion: v1
metadata:
  name: docs
  namespace: zgw
  labels:
    k8s-app: docs
spec:
  selector:
    k8s-app: docs
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
