---

# Runtime secrets. Values are base64 encoded

# kind: Secret
# apiVersion: v1
# metadata:
#   name: demo-secrets
#   namespace: zgw
# type: Opaque
# data:
#   SECRET_KEY: <REDACTED>
#   DB_PASSWORD: <REDACTED>
#   SENTRY_DSN: <REDACTED>

---

# Django app

kind: Deployment
apiVersion: apps/v1
metadata:
  name: demo
  namespace: zgw
  labels:
    k8s-app: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: demo
  template:
    metadata:
      name: demo
      labels:
        k8s-app: demo
    spec:
      containers:
        - name: demo
          image: vngr/gemma-zaken-demo:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "120Mi"
              cpu: "5m"
            limits:
              memory: "350Mi"
              cpu: "250m"
          # readinessProbe:
          #   httpGet:
          #     path: /admin/login/
          #     port: 8000
          #     httpHeaders:
          #       - name: Host
          #         value: localhost
          #   initialDelaySeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /admin/login/
          #     port: 8000
          #     httpHeaders:
          #       - name: Host
          #         value: localhost
          #   initialDelaySeconds: 10
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: zac.conf.docker
            - name: DB_HOST
              value: {{ db_host }}
            - name: DB_NAME
              value: demo
            - name: REDIS_HOST
              value: redis-demo
            - name: REDIS_PORT
              value: '6379'
            - name: IS_HTTPS
              value: "yes"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: demo-secrets
                  key: SECRET_KEY
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-secrets
                  key: DB_PASSWORD
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: demo-secrets
                  key: SENTRY_DSN

---

# Django app

kind: Service
apiVersion: v1
metadata:
  name: demo
  namespace: zgw
  labels:
    k8s-app: demo
spec:
  selector:
    k8s-app: demo
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
